title: "Master: Multimedia & Autorschaft"
email: info@mmautor.net
description: >- # this means to ignore newlines until "baseurl:"
  Beim Masterstudiengang Multimedia und Autorschaft in Halle (Saale) kommen medienaffine Menschen aus unterschiedlichen Fachrichtungen zusammen, um die Themen der digitalen Gegenwart zu erforschen und in journalistischen Projekten zu reflektieren.
url: https://dev-mma.soerenengels.de
# change necessary in robots.txt + head-seo.html
testurl: "https://dev-mma.soerenengels.de"
imageurl: /assets/images/
github_username: mmautor

# Spracheinstellungen
languages:
  active: false
  possibilities:
    de:
      short: de
      label: "DE"
      slug: ""
    en:
      short: en
      label: "EN"
      slug: "/en"

# Einstellungen zu Suchmaschinenoptimierung
seo:
  twitter:
    handle: mmautor
    card: summary_large_image
    image: social/twitter_card_summary-large.png

# Default-Einstellungen
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      lang: "de"
  - scope:
      path: "en"
    values:
      lang: "en"

# Build-Einstellungen
permalink: pretty
exclude: ["README.md"]
plugins:
  - jekyll-target-blank
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-admin
